//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SailingSales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boat
    {
        public Boat()
        {
            this.Customers = new HashSet<Customer>();
        }
    
        public string Description { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Length { get; set; }
        public Nullable<decimal> Beam { get; set; }
        public Nullable<decimal> Draft { get; set; }
        public string Hull { get; set; }
        public Nullable<int> Price { get; set; }
        public string Pictures { get; set; }
        public int ID { get; set; }
    
        public virtual ICollection<Customer> Customers { get; set; }
    }
}
